# Kubernetes files
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: binary-tree-deployment
  namespace: dev
  labels:
    app: binary-tree
    version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binary-tree
      version: "1.0"
  template:
    metadata:
      labels:
        app: binary-tree
        version: "1.0"
    spec:
      containers:
        - name: binary-tree
          image: mauriballes/binary-tree:1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: binary-tree-service
  namespace: dev
spec:
  selector:
    app: binary-tree
    version: "1.0"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: binary-tree-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - tree.mauriballes.com
      secretName: tree-tls
  rules:
    - host: tree.mauriballes.com
      http:
        paths:
          - path: /
            backend:
              serviceName: binary-tree-service
              servicePort: 80
